#!/usr/bin/env python3

"""Drop: move file from loot to pwd"""

import sys
import shutil
from pathlib import Path

# bail early if no file
if len(sys.argv) < 2:
    print("You can't drop nothing")
    sys.exit()

# check loot folder exists
loot_path = Path.home() / "loot"
if not loot_path.is_dir():
    sys.exit()

# check if already exists in folder
check_file = Path.cwd() / sys.argv[1]
if check_file.is_file():
    print("File already exists")
    sys.exit()

# check file exists and move it
drop_file = Path.home() / "loot" / sys.argv[1]
current_dir = Path.cwd()
if drop_file.is_file():
    shutil.move(drop_file, current_dir)
    print("You dropped " + sys.argv[1])
else:
    print("no such file in loot dir")
    sys.exit()
