#!/usr/bin/env python3

import os
import shutil
from pathlib import Path

# set folder vars
loot_path = Path.home() / "loot"
current_dir = Path.cwd()

# check folder exists
if loot_path.is_dir():
    pass
else:
    loot_path.mkdir()

# list contents
rl = os.listdir(loot_path)

if not rl:
    print("You have nothing")
else:
    for i in rl:
        print("Runaway!")
        shutil.move(loot_path / i, current_dir)
