#!/usr/bin/env python3

"""Flee: move all from loot folder to pwd"""

import os
import sys
import shutil
from pathlib import Path

# bail early if no file
if len(sys.argv) < 2:
    print("You can't drop nothing")
    sys.exit()

# check folder exists
loot_path = Path.home() / "loot"
if not loot_path.is_dir():
    sys.exit()

# drop everything here
current_dir = Path.cwd()
rl = os.listdir(loot_path)

if not rl:
    print("You have nothing")
else:
    for i in rl:
        shutil.move(loot_path / i, current_dir)
    print("Runaway! (You dropped everything)")
