#!/usr/bin/env python3

"""list contents of loot folder"""

import os
import sys
from pathlib import Path

# check folder exists
loot_path = Path.home() / "loot"
if not loot_path.is_dir():
    print("You have no lootbox")
    sys.exit()

# list contents
rl = os.listdir(loot_path)

if not rl:
    print("You have nothing")
else:
    for i in rl:
        print(i)
