#!/usr/bin/env python3

import sys
import shutil
from pathlib import Path

# bail early if no file
if len(sys.argv) < 2:
    print("You can't take nothing")
    sys.exit()

# set folder path
loot_path = Path.home() / "loot"
take_file = Path.cwd() / sys.argv[1]

# check folder exists
if loot_path.is_dir():
    pass
else:
    loot_path.mkdir()

# check file exists
if take_file.is_file():
    print("You took", sys.argv[1])
    shutil.move(take_file, loot_path)
else:
    print("You can't take a file that doesn't exist")
    sys.exit()
