#!/usr/bin/env python3

"""Take: move file into loot folder"""

import sys
import shutil
from pathlib import Path

# bail early if no file
if len(sys.argv) < 2:
    print("You can't take nothing")
    sys.exit()

# check folder exists
loot_path = Path.home() / "lootbox"
if loot_path.is_dir():
    pass
else:
    loot_path.mkdir()

# check if already looted
check_file = Path.home() / "loot" / sys.argv[1]
if check_file.is_file():
    print("File already looted")
    sys.exit()

# check file exists
take_file = Path.cwd() / sys.argv[1]
if take_file.is_file():
    print("You took", sys.argv[1])
    shutil.move(take_file, loot_path)
else:
    print("You can't take a file that doesn't exist")
    sys.exit()
